site:
    title: "xmdhs's blog"
    subtitle: "就是一个博客"
    limit: 10
    theme: theme
    lang: zh
    url: "https://xmdhs.top"
    comment: username
    logo: "https://avatars0.githubusercontent.com/u/20377726"
    # link: "{category}/{year}/{month}/{day}/{title}.html"
    # root: "/blog"

authors:
    me:
        name: "xmdhs"
        intro: ""
        avatar: "https://avatars0.githubusercontent.com/u/20377726"

build:
    # output: "public"
    port: 8000
    # Copied files to public folder when build
    copy:
        - "source/images"
    # Excuted command when use 'ink publish'
    publish: |
        git add . -A
        git commit -m "update"
        git push origin
