name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Clone build
        uses: actions/checkout@v2
        with:
          ref: build
          path: build

      - name: Copy
        run: |
          mkdir -p ./build/blog/source
          cp ./*.md ./build/blog/source

      - name: build blog
        run: |
          cd ./build 
          chmod +x ink
          ./ink build

      - name: Clone gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: pages  

      - name: push
        run: |
          cp -r ./build/blog/public ./pages
          cd ./pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout gh-pages
          git add .
          git commit -m "new post"
          git push

         